language: rust
# TODO switch to stable (i.e. remove this line) when 1.31 is out
rust: beta

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_success:
  - bash ci/after-success.sh

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
